<?php

namespace Database\Seeders;

use App\Models\MarketItem;
use Illuminate\Database\Seeder;

class MarketItemSeeder extends Seeder
{
    public function run(): void
    {
        $tools = [
            [
                'name' => 'Nmap Guide',
                'description' => 'Comprehensive guide to using Nmap for network scanning and security auditing.',
                'category' => 'courses',
                'price' => 2.99,
                'price_ngn' => 1999.00,
                'image' => 'nmap.jpg',
                'purchases_count' => rand(50, 200),
                'external_link' => 'https://selar.com/393gf1',
                'status' => 'active',
            ],
            [
                'name' => 'Zeus Crypter',
                'description' => 'Advanced crypter for obfuscating malicious payloads.',
                'category' => 'software',
                'price' => 12.99,
                'price_ngn' => 11999.00,
                'image' => 'zeus.jpg',
                'purchases_count' => rand(20, 100),
                'external_link' => 'https://selar.com/8oc60t',
                'status' => 'active',
            ],
            [
                'name' => 'ATM Hacking Course',
                'description' => 'In-depth course on techniques for exploiting ATM vulnerabilities.',
                'category' => 'courses',
                'price' => 31.99,
                'price_ngn' => 30999.00,
                'image' => 'atm-hijack.jpg',
                'purchases_count' => rand(10, 50),
                'external_link' => 'https://selar.com/7b855e',
                'status' => 'active',
            ],
            [
                'name' => 'OTP Bypass Course',
                'description' => 'Learn methods to bypass one-time password authentication systems.',
                'category' => 'courses',
                'price' => 31.99,
                'price_ngn' => 30999.00,
                'image' => 'otp-hijack.jpg',
                'purchases_count' => rand(15, 60),
                'external_link' => 'https://selar.com/971ht1',
                'status' => 'active',
            ],
            [
                'name' => 'Foreign Number Vendor',
                'description' => 'Access to foreign phone numbers for various purposes.',
                'category' => 'services',
                'price' => 16.77,
                'price_ngn' => 15777.00,
                'image' => 'vendor.jpg',
                'purchases_count' => rand(30, 120),
                'external_link' => 'https://selar.com/0398vz',
                'status' => 'active',
            ],
            [
                'name' => 'Carding Course',
                'description' => 'Training on techniques for unauthorized credit card transactions.',
                'category' => 'courses',
                'price' => 21.99,
                'price_ngn' => 20999.00,
                'image' => 'carding.jpg',
                'purchases_count' => rand(25, 80),
                'external_link' => 'https://selar.com/713435',
                'status' => 'active',
            ],
            [
                'name' => 'SQL Injection Course',
                'description' => 'Master SQL injection techniques for web application penetration testing.',
                'category' => 'courses',
                'price' => 16.99,
                'price_ngn' => 15999.00,
                'image' => 'sql-injection.jpg',
                'purchases_count' => rand(40, 150),
                'external_link' => 'https://selar.com/143793',
                'status' => 'active',
            ],
            [
                'name' => 'Spamming Course',
                'description' => 'Learn advanced email and message spamming techniques.',
                'category' => 'courses',
                'price' => 31.99,
                'price_ngn' => 30999.00,
                'image' => 'spamming.jpg',
                'purchases_count' => rand(10, 70),
                'external_link' => 'https://selar.com/1z8420',
                'status' => 'active',
            ],
            [
                'name' => 'Facebook OTP Bypass',
                'description' => 'Guide to bypassing OTP verification on Facebook accounts.',
                'category' => 'tools',
                'price' => 5.07,
                'price_ngn' => 5777.00,
                'image' => 'facebook-bypass.jpg',
                'purchases_count' => rand(60, 180),
                'external_link' => 'https://selar.com/3938pm',
                'status' => 'active',
            ],
            [
                'name' => 'Hook Botnet',
                'description' => 'Botnet tool for distributed network operations.',
                'category' => 'software',
                'price' => 23.99,
                'price_ngn' => 22999.00,
                'image' => 'hook-botnet.jpg',
                'purchases_count' => rand(15, 50),
                'external_link' => 'https://selar.com/6x1h0e',
                'status' => 'active',
            ],
            [
                'name' => 'DDOS Tools',
                'description' => 'Collection of tools for distributed denial-of-service attacks.',
                'category' => 'tools',
                'price' => 11.99,
                'price_ngn' => 10999.00,
                'image' => 'ddos.jpg',
                'purchases_count' => rand(30, 100),
                'external_link' => 'https://selar.com/1od781',
                'status' => 'active',
            ],
            [
                'name' => 'Vip Rat',
                'description' => 'Remote access tool for advanced system control (pending release).',
                'category' => 'software',
                'price' => 36.99,
                'price_ngn' => 35999.00,
                'image' => 'vip.jpg',
                'purchases_count' => 0,
                'external_link' => 'https://selar.com/90z3c8',
                'status' => 'pending',
            ],
            [
                'name' => 'Ransomware Builder',
                'description' => 'Tool to create custom ransomware payloads.',
                'category' => 'software',
                'price' => 24.99,
                'price_ngn' => 23999.00,
                'image' => 'ransomware.jpg',
                'purchases_count' => rand(10, 40),
                'external_link' => 'https://selar.com/bigt17',
                'status' => 'active',
            ],
            [
                'name' => 'Screen Lock Builder',
                'description' => 'Create screen-locking malware for various platforms.',
                'category' => 'software',
                'price' => 5.99,
                'price_ngn' => 4999.00,
                'image' => 'sc-lock.jpg',
                'purchases_count' => rand(50, 150),
                'external_link' => 'https://selar.com/33fo59',
                'status' => 'active',
            ],
            [
                'name' => 'Paste Aza',
                'description' => 'Tool for managing and exploiting data dumps.',
                'category' => 'tools',
                'price' => 4.99,
                'price_ngn' => 3999.00,
                'image' => 'paste-aza.jpg',
                'purchases_count' => rand(70, 200),
                'external_link' => 'https://selar.com/77fbt2',
                'status' => 'active',
            ],
            [
                'name' => 'Xhunter v9',
                'description' => 'Advanced exploit framework for penetration testing.',
                'category' => 'tools',
                'price' => 3.99,
                'price_ngn' => 2999.00,
                'image' => 'xhunter.jpg',
                'purchases_count' => rand(60, 180),
                'external_link' => 'https://selar.com/28g77r',
                'status' => 'active',
            ],
            [
                'name' => 'Video Call Software',
                'description' => 'Custom software for manipulating video call interactions.',
                'category' => 'software',
                'price' => 11.77,
                'price_ngn' => 10777.00,
                'image' => 'f-video.jpg',
                'purchases_count' => rand(20, 80),
                'external_link' => 'https://selar.com/707132',
                'status' => 'active',
            ],
            [
                'name' => 'CraxsRat v7.7',
                'description' => 'Powerful remote administration tool.',
                'category' => 'software',
                'price' => 31.99,
                'price_ngn' => 30999.00,
                'image' => 'craxsrat.jpg',
                'purchases_count' => rand(5, 30),
                'external_link' => 'https://selar.com/yh13l1',
                'status' => 'active',
            ],
            [
                'name' => 'WhatsApp Crasher',
                'description' => 'Tool to disrupt WhatsApp messaging services.',
                'category' => 'tools',
                'price' => 3.77,
                'price_ngn' => 2777.00,
                'image' => 'wa-crash.jpg',
                'purchases_count' => rand(80, 220),
                'external_link' => 'https://selar.com/v48348',
                'status' => 'active',
            ],
            [
                'name' => 'WhatsApp Spy',
                'description' => 'Monitor and intercept WhatsApp communications.',
                'category' => 'software',
                'price' => 5.99,
                'price_ngn' => 4999.00,
                'image' => 'wa-spy.jpg',
                'purchases_count' => rand(40, 130),
                'external_link' => 'https://selar.com/nb5ko8',
                'status' => 'active',
            ],
            [
                'name' => 'Live Location Tracking',
                'description' => 'Real-time location tracking tool.',
                'category' => 'software',
                'price' => 12.99,
                'price_ngn' => 11999.00,
                'image' => 'location-track.jpg',
                'purchases_count' => rand(15, 60),
                'external_link' => 'https://selar.com/o13rxd',
                'status' => 'active',
            ],
            [
                'name' => 'PC Destroyer',
                'description' => 'Malware tool for system disruption.',
                'category' => 'software',
                'price' => 4.99,
                'price_ngn' => 3999.00,
                'image' => 'pc-crash.jpg',
                'purchases_count' => rand(10, 50),
                'external_link' => 'https://selar.com/143793',
                'status' => 'active',
            ],
            [
                'name' => 'Email Extractor',
                'description' => 'Extract email addresses from various sources.',
                'category' => 'tools',
                'price' => 11.77,
                'price_ngn' => 10777.00,
                'image' => 'email extractor.jpg',
                'purchases_count' => rand(30, 100),
                'external_link' => 'https://selar.com/bw333v',
                'status' => 'active',
            ],
            [
                'name' => 'P.bank',
                'description' => 'Tool for banking-related operations.',
                'category' => 'tools',
                'price' => 4.77,
                'price_ngn' => 3777.00,
                'image' => 'p.bank.jpg',
                'purchases_count' => rand(50, 150),
                'external_link' => 'https://selar.com/544l5a',
                'status' => 'active',
            ],
            [
                'name' => 'Angry IP Scanner',
                'description' => 'Network scanning tool for IP enumeration.',
                'category' => 'tools',
                'price' => 6.77,
                'price_ngn' => 5777.00,
                'image' => 'angry-ip.jpg',
                'purchases_count' => rand(60, 180),
                'external_link' => 'https://selar.com/mna53y',
                'status' => 'active',
            ],
            [
                'name' => 'Bulk Mailer',
                'description' => 'Mass email sending tool.',
                'category' => 'tools',
                'price' => 16.99,
                'price_ngn' => 15999.00,
                'image' => 'bulkmailer.jpg',
                'purchases_count' => rand(20, 80),
                'external_link' => 'https://selar.com/22282w',
                'status' => 'active',
            ],
            [
                'name' => 'Burpsuite Pro',
                'description' => 'Professional web vulnerability scanner.',
                'category' => 'software',
                'price' => 31.99,
                'price_ngn' => 30999.00,
                'image' => 'burpsuite.jpg',
                'purchases_count' => rand(10, 50),
                'external_link' => 'https://selar.com/32a336',
                'status' => 'active',
            ],
            [
                'name' => 'BTC Flasher',
                'description' => 'Tool for simulating Bitcoin transactions (pending release).',
                'category' => 'software',
                'price' => 221.99,
                'price_ngn' => 225999.00,
                'image' => 'btc-flasher.jpg',
                'purchases_count' => 0,
                'external_link' => 'https://selar.com/717cj7',
                'status' => 'pending',
            ],
            [
                'name' => 'SQLi Dumper',
                'description' => 'Automated tool for SQL injection data extraction.',
                'category' => 'tools',
                'price' => 12.99,
                'price_ngn' => 11999.00,
                'image' => 'sqli-dumper.jpg',
                'purchases_count' => rand(30, 100),
                'external_link' => 'https://selar.com/4ml711',
                'status' => 'active',
            ],
            [
                'name' => 'ID Card Maker',
                'description' => 'Software for creating custom ID cards.',
                'category' => 'tools',
                'price' => 4.99,
                'price_ngn' => 3999.00,
                'image' => 'idcard.jpg',
                'purchases_count' => rand(50, 150),
                'external_link' => 'https://selar.com/989k99',
                'status' => 'active',
            ],
            [
                'name' => 'Sms Sender Pro',
                'description' => 'Professional SMS messaging tool.',
                'category' => 'tools',
                'price' => 13.99,
                'price_ngn' => 11999.00,
                'image' => 'sms sender.jpg',
                'purchases_count' => rand(20, 80),
                'external_link' => 'https://selar.com/d1881v',
                'status' => 'active',
            ],
            [
                'name' => 'RDP Stealer',
                'description' => 'Tool for extracting Remote Desktop Protocol credentials.',
                'category' => 'tools',
                'price' => 14.99,
                'price_ngn' => 13999.00,
                'image' => 'rdp.jpg',
                'purchases_count' => rand(15, 60),
                'external_link' => 'https://selar.com/uvocov',
                'status' => 'active',
            ],
            [
                'name' => 'Foreign Number',
                'description' => 'Access to international phone numbers.',
                'category' => 'services',
                'price' => 9.22,
                'price_ngn' => 8222.00,
                'image' => 'number.jpg',
                'purchases_count' => rand(40, 120),
                'external_link' => 'https://selar.com/446l7m',
                'status' => 'active',
            ],
            [
                'name' => 'Wifi Hacking',
                'description' => 'Course on wireless network penetration testing.',
                'category' => 'courses',
                'price' => 11.99,
                'price_ngn' => 10999.00,
                'image' => 'wifi.jpg',
                'purchases_count' => rand(50, 150),
                'external_link' => 'https://selar.com/3r8125',
                'status' => 'active',
            ],
        ];

        foreach ($tools as $tool) {
            MarketItem::updateOrCreate(['name' => $tool['name']], $tool);
        }
    }
}
